### ISSUE TITLE
layer_reconstruction() got an unexpected keyword argument 'timesteps'

### ISSUE THREAD

**Issue by colorjam** [hatchetProject/QuEST#4]
Hi, I set --quant_act in script but get the following error:
![image](https://github.com/hatchetProject/QuEST/assets/23700012/3f754012-f1b0-4d1e-9808-e25a1e0f8fd6)

**Comment by hatchetProject** [comment]
Hi, for our method, we do not use activation reconstruction (see this [line](https://github.com/hatchetProject/QuEST/blob/6d6821aee809aa0b5e24278c1aa3c3b43b92a7af/txt2img.py#L537)). 

If you would like to use the commented code, you can delete the timesteps argument in kwargs (line 541).

**Comment by colorjam** [comment]
@hatchetProject Thanks for your answer. I try again for weight-only quantization, but meet another error when saving parameters:
![image](https://github.com/hatchetProject/QuEST/assets/23700012/d7851678-84c5-411c-8afe-c17a5e718b84)

**Comment by hatchetProject** [comment]
Hi, if you are using weight-only quantization (not including the command of --quant_act), then comment out the line of:
```
qnn.save_dict_params()
```
This line is meant for saving the quantization parameters of the activation quantizers. Since you are doing weight-only quantization, the activation quantization parameters are not initialized and will be None, leading to the error.

I have also made changes in the repo's code of txt2img.py to deal with this issue.
